# For more information: https://laravel.com/docs/sail
version: '3'
services:
    php:
        container_name: bakis_php
        build:
            context: .
            dockerfile: docker/8.1/Dockerfile
            args:
                - user=donatas
                - uid=1000
        image: donatas/barbershop_php:latest
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - "9000:9000"
            - "5000:5000"
        volumes:
            - '.:/var/www/html'
            - './docker/8.1/conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini'
        restart: on-failure
        networks:
            - sail
        depends_on:
            - mysql
            - redis
    nginx:
        container_name: bakis_nginx
        image: bitnami/nginx:latest
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - '.:/var/www/html'
            - './docker/8.1/nginx.conf:/opt/bitnami/nginx/conf/server_blocks/nginx.conf'
        depends_on:
            - php
        networks:
            - sail
    mysql:
        container_name: bakis_mysql
        image: 'bitnami/mariadb:latest'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MARIADB_ROOT_PASSWORD: '${DB_PASSWORD}'
            MARIADB_ROOT_HOST: "%"
            MARIADB_DATABASE: '${DB_DATABASE}'
            MARIADB_USER: '${DB_USERNAME}'
            MARIADB_PASSWORD: '${DB_PASSWORD}'
            MARIADB_ALLOW_EMPTY_PASSWORD: 0
            MARIADB_SKIP_TEST_DB: yes
        volumes:
            - 'mysql:/bitnami/mariadb'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s

    redis:
        image: 'redis:alpine'
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s
    mailhog:
        image: 'mailhog/mailhog:latest'
        networks:
            - sail
networks:
    sail:
        driver: bridge
volumes:
    mysql:
        driver: local
    sail-redis:
        driver: local
