# For more information: https://laravel.com/docs/sail
version: '3'
services:
    php:
        container_name: bakis_php
        build:
            context: .
            dockerfile: docker/8.1/Dockerfile
        image: donatas/barbershop_php:latest
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - "8080:80"
        volumes:
            - '.:/var/www/html'
        restart: always
        networks:
            - sail
        depends_on:
            - mysql
            - redis
    mysql:
        container_name: bakis_mysql
        image: 'bitnami/mariadb:latest'
        ports:
            - '${FORWARD_DB_PORT:-3307}:3306'
        environment:
            MARIADB_ROOT_PASSWORD: '${DB_PASSWORD}'
            MARIADB_ROOT_HOST: "%"
            MARIADB_DATABASE: '${DB_DATABASE}'
            MARIADB_USER: '${DB_USERNAME}'
            MARIADB_PASSWORD: '${DB_PASSWORD}'
            MARIADB_ALLOW_EMPTY_PASSWORD: 0
        volumes:
            - 'mysql:/bitnami/mariadb'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s
    mailhog:
        image: 'mailhog/mailhog:latest'
        ports:
            - '${FORWARD_MAILHOG_PORT:-1025}:1025'
            - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
        networks:
            - sail
networks:
    sail:
        driver: bridge
volumes:
    mysql:
        driver: local
    sail-redis:
        driver: local
