name: CI
 
on:
  - pull_request
  - push
  
jobs:
  tests:
      name: Tests
 
      runs-on: ubuntu-latest
      
      steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            fetch-depth: 0
        - name: Init configuration file
          run: cp .env.example .env
          
        - name: Build the Docker image
          run: docker-compose build
            
        - name: Start containers
          run: docker-compose up -d
          
        - name: Install dependencies
          run: docker exec bakis_php composer install
          
        - name: Run tests with phpunit/phpunit
          run: php artisan test --coverage-clover=coverage.xml
          
        - name: Fix code coverage paths
          run: sed -i 's@'$GITHUB_WORKSPACE'@/github/workspace/@g' coverage.xml
          
        - name: SonarCloud Scan
          uses: SonarSource/sonarcloud-github-action@master
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
